version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: yt_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: yt_discovery
      POSTGRES_USER: yt_user
      POSTGRES_PASSWORD: yt_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yt_user -d yt_discovery"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
